### PR TITLE
protoc-gen-tstypes: Generating types for nested messages

### PR DESCRIPTION
**Pull request by mousavian**
I have also added a test file for the same purpose.

It also could be more simple like below, but I followed the same as NestedEnums. I can modify both. Let me know which one you prefer.

```golang
g.generateEnums(m.GetNestedEnumTypes(), params)
g.generateMessages(m.GetNestedMessageTypes(), params)
```

### CODE REVIEW

**Comment by mousavian** [comment]
Hey @tmc, any chance you may have time to check this? tia.

**Comment by tmc** [comment]
@mousavian thanks for this contribution. I wonder if we should be namespacing more strongly such as Location_Country -- we could have collisions otherwise. Can you add a test file with the same name for a sub-message?

**Comment by mousavian** [comment]
Sorry for late reply @tmc, 
TBH I think since these are nested messages/enums, collision shouldn't happen with other definitions, defined out of that scope.
In fact, this is exactly the same issue that I have already raised here #20, and is not happening when using other generators like [ts-protoc-gen](https://github.com/improbable-eng/ts-protoc-gen)

**Comment by tmc** [comment]
Sorry I missed the notification here. Need some sleep but I will review this in the morning.

**Comment by tmc** [comment]
@mousavian can you review https://github.com/tmc/grpcutil/pull/23 ?

**Comment by mousavian** [comment]
Great job and thanks for spending time on this @tmc .
I will close this PR.

**Pull request closed without merging**
