### PR TITLE
Add nullable option for flowtypes generator

### PR DESCRIPTION
**Pull request by gabriel**
In go, the grpc plugin uses pointers for all fields, and so for generating corresponding flow types, it's nice to default to nullable true for the proto options for everything. 

```
protoc -I. -I${GOPATH}/src --flowtypes_opt=nullable=true file.proto
```

### CODE REVIEW

**Comment by tmc** [comment]
Sorry I missed this. The path renamed would make this in-mergable as-is.

**Comment by tmc** [comment]
I like this change but it contains more than the PR description. Can you separate the redux code generation (which I really like) from the default change?

**Comment by tmc** [comment]
@gabriel ping

**Comment by gabriel** [comment]
I ended up not needing this because in proto3 everything is nullable (in golang) if not set, automatically.

The other changes for generating redux actions, reducers, etc I did without setting up branch which is why they showed up here.

Are you interested in those changes? I can do a PR for that next week sometime if so.

**Pull request closed without merging**
